/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { PermissionMatrix } from '@/types/permissions';

export const PERMISSION_MATRIX: PermissionMatrix = {
  'dashboard.view': 'all',
  'requests.create': 'all',
  'requests.view_own': 'all',
  'requests.view_assigned': [
    'dept_head',
    'head_nurse',
    'accountant',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'chief_accountant',
    'internal_accountant',
    'hr_records',
    'director',
    'chairman',
    'super_admin',
  ],
  'requests.view_all': ['chief_accountant', 'director', 'chairman', 'super_admin'],
  'approvals.review_assigned': [
    'dept_head',
    'head_nurse',
    'accountant',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'chief_accountant',
    'director',
    'chairman',
    'super_admin',
  ],
  'approvals.approve': [
    'dept_head',
    'head_nurse',
    'accountant',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'chief_accountant',
    'director',
    'chairman',
    'super_admin',
  ],
  'approvals.reject': [
    'dept_head',
    'head_nurse',
    'accountant',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'chief_accountant',
    'director',
    'chairman',
    'super_admin',
  ],
  'approvals.forward_manual': ['chief_accountant', 'director', 'chairman', 'super_admin'],
  'approvals.receive_handoff': ['internal_accountant', 'hr_records', 'super_admin'],
  'room_management.view_map': 'all',
  'room_management.create_material_intake': 'all',
  'room_management.create_maintenance_intake': 'all',
  'room_management.review_group_queue': [
    'head_nurse',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'chief_accountant',
    'super_admin',
  ],
  'room_management.consolidate_materials': [
    'head_nurse',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'super_admin',
  ],
  'room_management.print_material_summary': [
    'head_nurse',
    'pharmacy_head',
    'accounting_supervisor',
    'lab_head',
    'chief_accountant',
    'super_admin',
  ],
  'pharmacy.view': ['head_nurse', 'pharmacy_head', 'chief_accountant', 'director', 'chairman', 'super_admin'],
  'pharmacy.operate': ['pharmacy_head', 'super_admin'],
  'inventory.view': [
    'head_nurse',
    'accountant',
    'pharmacy_head',
    'accounting_supervisor',
    'chief_accountant',
    'internal_accountant',
    'director',
    'chairman',
    'super_admin',
  ],
  'inventory.operate': ['head_nurse', 'super_admin'],
  'valuation.view': ['accountant', 'accounting_supervisor', 'chief_accountant', 'internal_accountant', 'director', 'chairman', 'super_admin'],
  'weekly_report.view': ['head_nurse', 'accountant', 'lab_head', 'chief_accountant', 'internal_accountant', 'director', 'chairman', 'super_admin'],
  'weekly_report.operate': ['head_nurse', 'super_admin'],
  'lab_dashboard.view': ['lab_head', 'director', 'chairman', 'super_admin'],
  'lab_dashboard.operate': ['lab_head', 'super_admin'],
  'tv_management.view': ['super_admin'],
  'portal.view': 'all',
  'admin.view': ['super_admin'],
  'admin.manage': ['super_admin'],
};
